DELETE FROM bookmarks;
DELETE FROM feeds;
DELETE FROM users;
DELETE FROM links;
ALTER SEQUENCE users_id_seq RESTART WITH 1;
ALTER SEQUENCE links_id_seq RESTART WITH 1;
ALTER SEQUENCE bookmarks_id_seq RESTART WITH 1;
ALTER SEQUENCE feeds_id_seq RESTART WITH 1;